server:
  port: 8070
spring:
  profiles:
    active: git
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://configserver:8888/eureka/
      secondZone: http://${eureka.instance.hostname}:${server.port}/eureka/
