spring:
  application:
    name: note
  profiles:
    active: git
logging:
  level:
    org:
      springframework:
        security: DEBUG
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: notes
      port: 27018
      host: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    status:
      http-mapping:
        UP: 200