server:
  port: 8081
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8070/eureka
      defaultZone: http://eureka:8070/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/patientdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: git
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    status:
      http-mapping:
        UP: 200
