server:
  port: 8080
spring:
  profiles:
    active: git
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    status:
      http-mapping:
        UP: 200
logging:
  level:
    org:
      springframework:
        security: DEBUG
