server:
  port: 8080
spring:
  profiles:
    active: git
  web:
    resources:
      static-locations: classpath:/static/
      templates-locations: classpath:/templates/
  datasource:
    url: jdbc:mysql://localhost:3308/userdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka # version pour IDE
      #defaultZone: http://eurekaserver:8070/eureka # version pour container
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    status:
      http-mapping:
        UP: 200
logging:
  level:
    org:
      springframework:
        security: DEBUG
