server:
  port: 8080
spring:
  profiles:
    active: git
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka # version pour IDE
      #defaultZone: http://eurekaserver:8070/eureka # version pour container
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    status:
      http-mapping:
        UP: 200
